config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'restaurants#index'
  resources :restaurants do
    resources :reviews
  end
  

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  validates :name, presence: true
  # validates :location, presence: true

  def average_score
    return 'No reviews' if reviews.none?
    reviews.average(:rating)
    
    # total_score = reviews.inject(0) do |total, review|
    #   total += review.rating
    # end
    # total_score / reviews.length
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  # validates :comment, presence: true
  validates :rating, inclusion: { in: [1,2,3,4,5] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  # before_action :authenticate_user!, except: [:index]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to '/restaurants'
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find params[:id]
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    @restaurant = Restaurant.find params[:id]

    @restaurant.update restaurant_params
    flash[:notice] = 'Restaurant updated successfully!'
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find params[:id]
    @restaurant.destroy

    flash[:notice] = 'Restaurant deleted successfully!'
    redirect_to '/restaurants'
  end

  private

  def restaurant_params
    params[:restaurant].permit(:name, :location, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant.reviews.create params[:review].permit(:rating, :comment)

    redirect_to '/restaurants'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def star_rating(rating)
    return rating unless rating.respond_to? :round
    
    rounded_rating = rating.round

    empty_stars = '☆' * (5 - rounded_rating)
    ('★' * rounded_rating) + empty_stars
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cool Yelpclone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">YelpApp</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li>Logged in as <%= current_user.email %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



<div class='container'>
  <%= yield %>
</div>

</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class='row'>
  <% if @restaurants.any? %>
    <% @restaurants.each do |restaurant| %>

      <div class='col-md-4'>
        <h1><%= link_to restaurant.name, restaurant_path(restaurant) %></h1>

        <%= link_to 'Edit', edit_restaurant_path(restaurant), class: 'btn btn-primary' %>

        <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> 

        <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant), class: 'btn btn-success' %>

        <h3 class='average_review'>
          <%= star_rating(restaurant.average_score) %>
        </h3>
      </div>
    <% end %>
  <% else %>
    No restaurants yet
  <% end %>
</div>

<br>
<%= link_to 'Add a restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.comment %> (<%= review.rating %>/5)</li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment %>

  <br>

  <%= f.label :rating %>
  <%= f.select :rating, 1..5 %>

  <%= f.submit %>

<% end %>